name: Links

on:

  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, ready_for_review, review_requested, review_request_removed ]

  schedule:
    - cron: "00 09 * * *"  # Run at 9:00 AM every day

permissions: read-all

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links with lychee
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: "--base . --cache --max-cache-age 1d ."